@echo off
echo Creating lock file...
echo running > running.lock
title Celebimew's Addons RPC Helper
cd /d "%~dp0"
echo Installing dependencies...
pip install pypresence toml
echo Running script...
python RpcHelper.py
echo Deleting lock file...
del running.lock
pause
